// Try catch 


const numero1 = 20;
const numero3 = 30;



console.log(numero1);
try {              //intentar hacer algo
    console.log(numero2);
}catch(error){      //cae el error
    console.log(error);
}
console.log(numero3);

